steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/smart-cater-backend/backend-streamlit:v0.7.0'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/smart-cater-backend/backend-streamlit:v0.7.0'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/smart-cater-backend/backend-streamlit:v0.7.0'
